added option for uppercase titles
riggraz/no-style-please pull request #21
Opened 2021-04-15 00:54 UTC by craigeley

Resolves #11

2021-05-23 15:58 UTC, EchedeyLR commented
Would be preferable an option for that and other to maintain the exact format I gave to the title in the post header.

2021-06-03 14:42 UTC, craigeley commented
> Would be preferable an option for that and other to maintain the exact format I give to the title in the post header.

That is how this functions. If lowercase titles is set to false than it will show them as they appear in your post YAML.

2021-06-03 14:49 UTC, EchedeyLR commented
Aaaaaag sorry.

I read it wrong and thought that were put in uppercase if I dont choose to set them in lowercase.

2023-09-02 15:30 UTC, EchedeyLR commented
Is there any update to this?

2024-12-29 13:16 UTC, tanvincible requested changes
I believe you have accidently pushed `.DS_Store`, otherwise the PR looks good to me.

2025-01-01 11:07 UTC, tanvincible approved these changes

2025-01-01 11:08 UTC, tanvincible commented
Thanks @craigeley for the PR!

2025-01-01 11:08 UTC, merged